name: Auto Changelog

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install rcgen
        run: cargo install --git https://github.com/neuxdotdev/rcgen.git

      - name: Generate changelog
        run: rcgen gen -o CHANGELOG.md

      - name: Commit changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "neuxdotdev-bot"
          git config user.email "noreply@neuxdotdev.my.id"
          git add CHANGELOG.md
          git diff --quiet && echo "No changes to commit" || git commit -m "docs(changelog): auto update $(date '+%d/%m/%Y %H:%M:%S')"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
