name: Auto Changelog

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install rcgen
        run: cargo install --git https://github.com/neuxdotdev/rcgen.git

      - name: Generate changelog
        run: rcgen gen -o CHANGELOG.md

      - name: Push changelog to repo
        uses: justjavac/action-gh-push@v1
        with:
          files: |
            CHANGELOG.md
          fail_on_unmatched_files: false
          repository: ${{ github.repository }}
          commit_message: "docs(changelog): auto update ${{ github.run_number }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
